name: ECS Deploy 

on:
  repository_dispatch:
    types: ["deploy_ecs"]

jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Print commit SHA
      run: |
        echo "Commit SHA: ${{ github.event.client_payload.sha }}"